import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from 'next-auth'
import Link from 'next/link'
import Logout from './logout'
import AuthProvider from './AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
      <html lang="en">
        <body className={inter.className}>
          <AuthProvider>
            <nav>
              {!!session &&
                <Logout/>
              }
              {!session &&
                <Link href='/login'>
                  Login
                </Link>
              }
            </nav>
            {children}
          </AuthProvider>
          </body>
      </html>
  )
}
